spring:
  config:
    activate:
      on-profile: local
  application:
    name: dash
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:dash


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-valid-time: ${ACCESS_TOKEN_VALID_TIME}
  refresh-token-valid-time: ${REFRESH_TOKEN_VALID_TIME}

kakao:
  client-id: ${KAKAO_CLIENT_ID}

s3:
  secret-key: ${SECRET_KEY}
  access-key: ${ACCESS_KEY}
  s3-endpoint: ${S3_ENDPOINT}
  region: ${REGION}
  s3-bucket-name: ${S3_BUCKET_NAME}

naver:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}

toss:
  client_id: ${TOSS_CLIENT_ID}
  payment_uri: ${TOSS_PAYMENT_URI}
  connection-timeout: ${CONNECTION_TIMEOUT}
  read-timeout: ${READ_TIMEOUT}
  socket-timeout: ${SOCKET_TIMEOUT}
  cancel-uri: ${TOSS_CANCEL_URI}

solapi:
  api-key: ${SOLAPI_API_KEY}
  api-secret: ${SOLAPI_API_SECRET}
  base-url: https://api.solapi.com
  from: ${SOLAPI_SENDER_PHONE}
  verification-template: ${SOLAPI_VERIFICATION_TEMPLATE}
  templates:
    class-apply: "[TEST] %s님의 %s 클래스에 신청자 %s (%s)가 신청했습니다."
    class-confirmed: "[TEST] %s님, %s 강사의 %s 수강이 확정되었습니다."
    class-cancelled-by-system: "[TEST] %s님, %s 강사의 %s 신청이 자동 취소되었습니다."
    class-cancelled-by-student: "[TEST] %s님, %s 클래스 수강생 %s (%s)가 환불 요청 (%s / %s)을 보냈습니다."
    class-cancel-done: "[TEST] %s님, %s 강사가 %s 신청을 취소 완료 처리했습니다. 환불 계좌: %s"
